### ISSUE TITLE
How to best update EXMARaLDA dependency?

### ISSUE THREAD

**Issue by berndmoos** [hzsk/HZSK-CLARIN-Services#2]
If there is a bug in the web service code, it is usually something in the EXMARaLDA.jar. When I fix this, I build a new EXMARaLDA.jar (from another project) and choose "Manually install artefact" from the context menu (in NetBeans) and then simply browse to the local EXMARaLDA.jar. I'm not sure if this makes sense, particularly I'm not sure if and how others working with the MAVEN project will be able to see and use the changes made in the EXMARaLDA.jar. Can the MAVEN wisemen please explain?

**Comment by hzsk-dj** [comment]
I honestly do not know how to best deal with this. Maybe @flammie or @nikopartanen have an idea?
I am not sure if fine-grained versioning of EXMARaLDA-builts (cf. [semantic versioning](http://semver.org/)) could be feasible or if it might be helpful!? But probably not.

**Comment by nikopartanen** [comment]
I don't know either if version numbers in EXMARaLDA jar-filenames could help in keeping it sorted? Or maybe there could be some mechanism to distribute information that there is a new EXMARaLDA build with list of changes? I don't know if anyone here is building EXMARaLDA on regular basis so if you are doing that often maybe you could add the most recent development build somewhere, maybe like [this](https://help.github.com/articles/creating-releases/)?
